### ISSUE TITLE
(4.0.0-RC3) NoSuchFieldError when trying to send a document

### ISSUE THREAD

**Issue by thierryvt** [difi/oxalis#314]
Everything works fine with RC2 but RC3 has some improvements and bugfixes I want.
So I simply changed the version in the main POM, everything builds just fine but when I try to send a file I get below exception:

`Exception in thread "main" java.lang.NoSuchFieldError: GOST3411_2012_256
	at org.bouncycastle.mail.smime.SMIMESignedGenerator.<clinit>(Unknown Source)
	at no.difi.oxalis.as2.util.SMimeMessageFactory.createSignedMimeMessage(SMimeMessageFactory.java:115)
	at no.difi.oxalis.as2.outbound.As2MessageSender.prepareHttpRequest(As2MessageSender.java:174)
	at no.difi.oxalis.as2.outbound.As2MessageSender.send(As2MessageSender.java:144)
	at no.difi.oxalis.as2.outbound.As2MessageSenderFacade.send(As2MessageSenderFacade.java:58)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:130)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:95)
	at eu.sendregning.oxalis.OutboundServer.send(OutboundServer.java:342)
	at eu.sendregning.oxalis.OutboundServer.send(OutboundServer.java:305)
	at eu.sendregning.oxalis.OutboundServer.processCustomer(OutboundServer.java:212)
	at eu.sendregning.oxalis.OutboundServer.detectAndProcessCustomers(OutboundServer.java:123)
	at eu.sendregning.oxalis.OutboundServer.run(OutboundServer.java:86)
	at eu.sendregning.oxalis.Main.main(Main.java:44)`

Anyone else had this issue or know how to resolve it?

(edit: formatting)

**Comment by thierryvt** [comment]
the culprit is this call:

`SMIMESignedGenerator smimeSignedGenerator = new SMIMESignedGenerator("binary");`

I copied this piece of code to a local class to try and run it.

When I'm referencing RC2 it works, as soon as I reference RC3 it throws the aforementioned exception.

**Comment by klakegg** [comment]
Bouncy castle is downgraded for upcoming release. Should fix this problem.

**Comment by thierryvt** [comment]
Still had the issue on 4.0.0 (full release). I checked out the sourcecode and had to downgrade bouncycastle one more version to 1.56 to get it to work.

**Comment by thierryvt** [comment]
unfortunately didn't fix it. Still getting the same exception.

`java.lang.NoSuchFieldError: id_Gost28147_89_None_KeyWrap
	at org.bouncycastle.cms.CMSAlgorithm.<clinit>(Unknown Source)
	at org.bouncycastle.mail.smime.SMIMESignedGenerator.<clinit>(Unknown Source)
	at no.difi.oxalis.as2.util.SMimeMessageFactory.createSignedMimeMessage(SMimeMessageFactory.java:115)
	at no.difi.oxalis.as2.outbound.As2MessageSender.prepareHttpRequest(As2MessageSender.java:174)
	at no.difi.oxalis.as2.outbound.As2MessageSender.send(As2MessageSender.java:144)
	at no.difi.oxalis.as2.outbound.As2MessageSenderFacade.send(As2MessageSenderFacade.java:58)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.perform(DefaultTransmitter.java:130)
	at no.difi.oxalis.outbound.transmission.DefaultTransmitter.transmit(DefaultTransmitter.java:95)
	at be.dynatos.OutboundServer.send(OutboundServer.java:345)
	...`

**Comment by thierryvt** [comment]
I've found the issue: my maven project is listing the wrong version of bcpkix-jdk15on, taking 1.59 and not 1.57.
Why it does this I don't know, looking through the sourcecode (of both my own project and the oxalis project) I can't find a single reference to 1.59.

JRE and JDK are up to date so that shouldn't be it, I'm also running the latest version of eclipse oxygen.

I did find a workaround, it's a hackjob but it works: in my local maven repository I simply make a copy of and rename 1.57 to 1.59.

If you know why it might be doing this, let me know.

**Comment by Nilsen89** [comment]
I had the same issue with `java.lang.NoSuchFieldError: id_Gost28147_89_None_KeyWrap`. I used Maven Central to only pull down the oxalis-outbound, and my bcpkix-jdk15on was version 1.59. Had to manually change to 1.57 to fix the issue.

```
<!-- Downgraded bcpkix-jdk15on because of:
 java.lang.NoSuchFieldError: id_Gost28147_89_None_KeyWrap -->
<dependency>
    <groupId>org.bouncycastle</groupId>
    <artifactId>bcpkix-jdk15on</artifactId>
    <version>1.57</version>
</dependency>
```
